name = "backend"
compatibility_date = "2024-08-13"

 [vars]
DATABASE_URL ="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjY0ZTQzNTQtOWIwZC00NTIxLTkwOTItZjUyMTYzYWVlZDI1IiwidGVuYW50X2lkIjoiYWZiZGI3ZDY4YTFjYjA2N2ZjZTQ0ZjczNDc0Yzk2ODcwODkwNWM5MjVlNzc4Nzk0MWQzNDQyMzE0ZTY0NzEzMCIsImludGVybmFsX3NlY3JldCI6ImIzYmU5NmU4LWNkYTUtNDBjMi1iOTExLTViNDU0YzVlYTM1OCJ9.Bg7f1zBX22y6E9ocJtXIHfsLJxeFZPB4XyUP8CvxpfE"
JWT_SECRET="adsdad"